services:
  flask:
    image: flights-app-docker-compose
    build: .
    container_name: flights-container-docker-compose
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1